# **Intro to Numpy**

### Importing Package

In [ ]:
import numpy as np

### Creating arrays

In [ ]:
#create an array of zeros with 10 elements 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#create an array of ones with 10 elements  
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#create an array of shape 10 and filled value 2.5 
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
#covert a list into an array
a= np.array([1,2,3,4,5,7,12])
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [ ]:
#access an element of an array 
a[2]

3

In [ ]:
#change an element 
a[2] = 10
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [ ]:
#create an array with spaced values within a given interval 
np.arange(3,10)
np.arange(3,10,2)

array([3, 5, 7, 9])

In [ ]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

**Multi-dimensional arrays**

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n=np.array([
          [1,2,3],
          [4,5,6],
          [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
n[0][0]

1

In [ ]:
n[1,:]

array([4, 5, 6])

**Randomly generated arrays**

In [ ]:
#create a random arrays with values rage between 0 and  1 with 2 colums and 5 rows 
np.random.rand(5,2)

array([[0.41031527, 0.44420257],
       [0.23468722, 0.95096066],
       [0.00456806, 0.70869762],
       [0.24958638, 0.32713484],
       [0.97477494, 0.74221171]])

In [ ]:
#we can fix the random values 
np.random.seed(2)
np.random.rand(5,2)


array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
np.random.seed(2)
np.random.randint(low = 0 ,high = 100 , size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
#add to every array element  
a + 1 

array([1, 2, 3, 4, 5])

In [ ]:
#multiply 
a * 2

array([0, 2, 4, 6, 8])

In [ ]:
10+((a *2)**2)

array([10, 14, 26, 46, 74])

In [ ]:
b = (10 + (a * 2 )) ** 2  / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
#combine 2 arrays 
a + b 


array([1.  , 2.44, 3.96, 5.56, 7.24])

### Comparison Operations

In [ ]:
a >= 2 

array([False, False,  True,  True,  True])

In [ ]:
 a = b 
 a 

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [ ]:
a > b 

array([False, False,  True,  True,  True])

In [ ]:
a
a[a>b]

array([2, 3, 4])

### Summarizing operations

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a.mean()

2.0

In [ ]:
a.std()

1.4142135623730951

In [ ]:
a.max()

4

# **Linear Algebra**

### Vector Operations

In [ ]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [ ]:
#addition
u + v 

array([3, 4, 5, 8])

**1. Vector-vector multiplication**

In [ ]:
#vector-vector multiplication ( dot product)
u * v 

array([ 2,  0,  0, 12])

In [ ]:
#return assertion error if the condition is not true 
assert u.shape[0] == v.shape[0]

In [ ]:
u.shape[0]

4

In [ ]:
v.shape[0]

4

In [ ]:
 def vector_vector_multiplication(u , v ):
   assert u.shape[0] == v.shape[0]
   n = u.shape[0]
   result  = 0.0
   for i in range(n):
     result = result + u[i] * v[i]
   return result


In [ ]:
vector_vector_multiplication(u , v )

14.0

**2. Marix-vector multiplication**

In [ ]:
U = np.array([
              [5,2,4,6],
              [1,2,1,2],
              [3,1,2,1]
])

In [ ]:
U.shape[0]

3

In [ ]:
U.shape[1]

4

In [ ]:
def matrix_vector_multiplication(U , v ):
   assert U.shape[1] == v.shape[0]
   num_rows = U.shape[0]
   result  = np.zeros(num_rows)
   for i in range(num_rows):
     result[i] = vector_vector_multiplication(U[i] , v )
   return result

In [ ]:
matrix_vector_multiplication(U , v )

array([17.,  5.,  5.])

In [ ]:
U.dot(v)

array([17,  5,  5])

In [ ]:
u.dot(v)

14

**3- matrix-matrix multiplication**

In [ ]:
V = np.array([
              [1,1,2],
              [0,0.5,1],
              [0,2,1],
              [2,1,0]             
              ])

In [ ]:
V.shape[0]

4

In [ ]:
V.shape[1]

3

In [ ]:
U.dot(V)

array([[17. , 20. , 16. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
def matrix_matrix_multiplication(U , V ):
   assert U.shape[1] == V.shape[0]
   num_rows = U.shape[0]
   num_cols = V.shape[1]
   result  = np.zeros((num_rows, num_cols))
   for i in range(num_cols):
     vi = V[:,i]
     Uvi = matrix_vector_multiplication(U , vi )
     result[:,i] = Uvi
   return result

In [ ]:
matrix_matrix_multiplication(U , V )

array([[17. , 20. , 16. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity matrix

In [ ]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse matrix

In [ ]:
 Vs = V[[0,1,2]]
 Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [ ]:
Vs_inv=np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [ ]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Intro to Pandas

### Importing package

In [1]:
import numpy as np
import pandas as pd

### Dataframes

#### Manipulating Dataframe 

In [2]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [3]:
df= pd.DataFrame(data  , columns = columns)
df

Make     Model  Year  ...  Transmission Type  Vehicle_Style   MSRP
0   Nissan    Stanza  1991  ...             MANUAL          sedan   2000
1  Hyundai    Sonata  2017  ...          AUTOMATIC          Sedan  27150
2    Lotus     Elise  2010  ...             MANUAL    convertible  54990
3      GMC    Acadia  2017  ...          AUTOMATIC        4dr SUV  34450
4   Nissan  Frontier  2017  ...             MANUAL         Pickup  32340

[5 rows x 8 columns]

In [4]:
df.head(2)

Make   Model  Year  ...  Transmission Type  Vehicle_Style   MSRP
0   Nissan  Stanza  1991  ...             MANUAL          sedan   2000
1  Hyundai  Sonata  2017  ...          AUTOMATIC          Sedan  27150

[2 rows x 8 columns]

In [5]:
df.Model

0      Stanza
1      Sonata
2       Elise
3      Acadia
4    Frontier
Name: Model, dtype: object

In [6]:
df["Model"]

0      Stanza
1      Sonata
2       Elise
3      Acadia
4    Frontier
Name: Model, dtype: object

In [7]:
#get a subset of our dataframe
df[['Make','Year']]

Make  Year
0   Nissan  1991
1  Hyundai  2017
2    Lotus  2010
3      GMC  2017
4   Nissan  2017

In [8]:
df['id'] = [1,2,3,4,5]
df

Make     Model  Year  ...  Vehicle_Style   MSRP id
0   Nissan    Stanza  1991  ...          sedan   2000  1
1  Hyundai    Sonata  2017  ...          Sedan  27150  2
2    Lotus     Elise  2010  ...    convertible  54990  3
3      GMC    Acadia  2017  ...        4dr SUV  34450  4
4   Nissan  Frontier  2017  ...         Pickup  32340  5

[5 rows x 9 columns]

In [9]:
del df['id']

#### Index

In [10]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [11]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
df.index = ['a','b','c','d','e']
df

Make     Model  Year  ...  Transmission Type  Vehicle_Style   MSRP
a   Nissan    Stanza  1991  ...             MANUAL          sedan   2000
b  Hyundai    Sonata  2017  ...          AUTOMATIC          Sedan  27150
c    Lotus     Elise  2010  ...             MANUAL    convertible  54990
d      GMC    Acadia  2017  ...          AUTOMATIC        4dr SUV  34450
e   Nissan  Frontier  2017  ...             MANUAL         Pickup  32340

[5 rows x 8 columns]

In [13]:
df.loc[['a','b']]

Make   Model  Year  ...  Transmission Type  Vehicle_Style   MSRP
a   Nissan  Stanza  1991  ...             MANUAL          sedan   2000
b  Hyundai  Sonata  2017  ...          AUTOMATIC          Sedan  27150

[2 rows x 8 columns]

In [14]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [15]:
df.reset_index()

index     Make     Model  ...  Transmission Type  Vehicle_Style   MSRP
0     a   Nissan    Stanza  ...             MANUAL          sedan   2000
1     b  Hyundai    Sonata  ...          AUTOMATIC          Sedan  27150
2     c    Lotus     Elise  ...             MANUAL    convertible  54990
3     d      GMC    Acadia  ...          AUTOMATIC        4dr SUV  34450
4     e   Nissan  Frontier  ...             MANUAL         Pickup  32340

[5 rows x 9 columns]

In [18]:
df = df.reset_index(drop = True)
df

Make     Model  Year  ...  Transmission Type  Vehicle_Style   MSRP
0   Nissan    Stanza  1991  ...             MANUAL          sedan   2000
1  Hyundai    Sonata  2017  ...          AUTOMATIC          Sedan  27150
2    Lotus     Elise  2010  ...             MANUAL    convertible  54990
3      GMC    Acadia  2017  ...          AUTOMATIC        4dr SUV  34450
4   Nissan  Frontier  2017  ...             MANUAL         Pickup  32340

[5 rows x 8 columns]

#### Accessing Elements 

####  Element wise operations 

In [20]:
df["Engine HP"] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

#### Filtering

In [21]:
df[df['Year'] >= 2015]

Make     Model  Year  ...  Transmission Type  Vehicle_Style   MSRP
1  Hyundai    Sonata  2017  ...          AUTOMATIC          Sedan  27150
3      GMC    Acadia  2017  ...          AUTOMATIC        4dr SUV  34450
4   Nissan  Frontier  2017  ...             MANUAL         Pickup  32340

[3 rows x 8 columns]

In [24]:
df[(df['Make'] == 'Nissan') &  (df['Year'] >= 2015)]

Make     Model  Year  ...  Transmission Type  Vehicle_Style   MSRP
4  Nissan  Frontier  2017  ...             MANUAL         Pickup  32340

[1 rows x 8 columns]

#### String operations

In [26]:
#lowercase
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [28]:
df['Vehicle_Style'].str.replace(' ','_').str.lower()

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: object

#### Summarizing operations

In [29]:
df.MSRP.max()

54990

In [32]:
#for nmerical values 
df.describe()

Year  Engine HP  Engine Cylinders          MSRP
count     5.000000    4.00000          5.000000      5.000000
mean   2010.400000  202.75000          4.400000  30186.000000
std      11.260551   51.29896          0.894427  18985.044904
min    1991.000000  138.00000          4.000000   2000.000000
25%    2010.000000  180.00000          4.000000  27150.000000
50%    2017.000000  206.00000          4.000000  32340.000000
75%    2017.000000  228.75000          4.000000  34450.000000
max    2017.000000  261.00000          6.000000  54990.000000

In [34]:
# how many uniq values in each column 
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
dtype: int64

#### Missing Values

In [35]:
df.isnull()

Make  Model   Year  ...  Transmission Type  Vehicle_Style   MSRP
0  False  False  False  ...              False          False  False
1  False  False  False  ...              False          False  False
2  False  False  False  ...              False          False  False
3  False  False  False  ...              False          False  False
4  False  False  False  ...              False          False  False

[5 rows x 8 columns]

In [36]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

#### Grouping 

In [ ]:
'''
 SELECT transmission_type , AVG(MSRP)
 FROM cars 
 GROUP BY transmission_type
 ''' 

In [38]:
df.groupby('Transmission Type').MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

### Getting the numpy arrays 

In [39]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [41]:
# convert the df to a dict 
df.to_dict(orient='records')

[{'Engine Cylinders': 4,
  'Engine HP': 138.0,
  'MSRP': 2000,
  'Make': 'Nissan',
  'Model': 'Stanza',
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'Year': 1991},
 {'Engine Cylinders': 4,
  'Engine HP': nan,
  'MSRP': 27150,
  'Make': 'Hyundai',
  'Model': 'Sonata',
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'Year': 2017},
 {'Engine Cylinders': 4,
  'Engine HP': 218.0,
  'MSRP': 54990,
  'Make': 'Lotus',
  'Model': 'Elise',
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'Year': 2010},
 {'Engine Cylinders': 4,
  'Engine HP': 194.0,
  'MSRP': 34450,
  'Make': 'GMC',
  'Model': 'Acadia',
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'Year': 2017},
 {'Engine Cylinders': 6,
  'Engine HP': 261.0,
  'MSRP': 32340,
  'Make': 'Nissan',
  'Model': 'Frontier',
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'Year': 2017}]

# summary of session 1 